name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1" # 每周一自动运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 4.5.1
        run: corepack prepare yarn@4.5.1 --activate

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build
